CREATE TABLE clothes(clothes_id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
description TEXT NOT NULL,
brand TEXT,
size TEXT NOT NULL,
color TEXT NOT NULL,
condition_comment TEXT,
uploaded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
)

CREATE TABLE users(
user_id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
email TEXT UNIQUE NOT NULL,
password TEXT NOT NULL,
created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
CHECK (LENGTH(password) >=6),
CHECK (LENGTH(name) >=2 )
)

CREATE TABLE loan(
loan_id SERIAL PRIMARY KEY,
clothes_id INTEGER NOT NULL,
user_id INTEGER NOT NULL,
loan_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
return_date DATE NOT NULL DEFAULT CURRENT_DATE + INTERVAL '7 days',
FOREIGN KEY (clothes_id) REFERENCES clothes(clothes_id),
FOREIGN KEY (user_id) REFERENCES users (user_id)
)
